#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : colcon-output
Version  : 0.2.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/38/ef/76bd921117e8ae8677fc5ad9a788bf014c2d8efd79e368e5bfe85455e35b/colcon-output-0.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/38/ef/76bd921117e8ae8677fc5ad9a788bf014c2d8efd79e368e5bfe85455e35b/colcon-output-0.2.0.tar.gz
Summary  : Extension for colcon to customize the output in various ways.
Group    : Development/Tools
License  : Apache-2.0
Requires: colcon-output-python3
Requires: colcon-output-python
Requires: colcon-core
BuildRequires : buildreq-distutils3

%description
=============

%package python
Summary: python components for the colcon-output package.
Group: Default
Requires: colcon-output-python3

%description python
python components for the colcon-output package.


%package python3
Summary: python3 components for the colcon-output package.
Group: Default
Requires: python3-core

%description python3
python3 components for the colcon-output package.


%prep
%setup -q -n colcon-output-0.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533002640
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
