#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : colcon-output
Version  : 0.2.4
Release  : 9
URL      : https://files.pythonhosted.org/packages/ec/74/3bba7207ab9a8fae552f0e8148fc3bc5a987331fe1145da917e75ef2eca3/colcon-output-0.2.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/ec/74/3bba7207ab9a8fae552f0e8148fc3bc5a987331fe1145da917e75ef2eca3/colcon-output-0.2.4.tar.gz
Summary  : Extension for colcon to customize the output in various ways.
Group    : Development/Tools
License  : Apache-2.0
Requires: colcon-output-python = %{version}-%{release}
Requires: colcon-output-python3 = %{version}-%{release}
Requires: colcon-core
BuildRequires : buildreq-distutils3
BuildRequires : colcon-core

%description
colcon-output
=============
An extension for `colcon-core <https://github.com/colcon/colcon-core>`_ to customize the output in various ways.

%package python
Summary: python components for the colcon-output package.
Group: Default
Requires: colcon-output-python3 = %{version}-%{release}

%description python
python components for the colcon-output package.


%package python3
Summary: python3 components for the colcon-output package.
Group: Default
Requires: python3-core

%description python3
python3 components for the colcon-output package.


%prep
%setup -q -n colcon-output-0.2.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1563420429
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
